### PR TITLE
Use GitHub actions to deploy to Netlify (and some more tweaks)

### PR DESCRIPTION
**Pull request by JonasVerbickas**
1. Screenshots have for the first workshop been updates with newer ones from the latest VM image.
2. New initial commit for [marauroa](https://github.com/arianne/marauroa) is set.
3. `_book/ ` directory has been added to `.gitignore`
4. Used GitHub actions are to deploy to Netlify

### CODE REVIEW

**Review by dullhunk — APPROVED** [review]

**Review by dullhunk — APPROVED** [review]

**Review by dullhunk — APPROVED** [review]

**Review by dullhunk — APPROVED** [review]

**Review by dullhunk — APPROVED** [review]

**Review by dullhunk — APPROVED** [review]

**Review by dullhunk — APPROVED** [review]

**Review by dullhunk — APPROVED** [review]

**Review by dullhunk — APPROVED** [review]

**Comment by suzanneEmbury** [comment]
I deleted the _book folder and that seemed to resolve all the conflicts.  Then I completed the merge.

But I didn't have a local environment in which I could test the contents of the merge before doing the merge, so I have no evidence that we're actually in a good place right now.  I may have caused some problems by this merge that will need to be detected and fixed.  Hopefully the CI will tell us that soon?

Let me know if you need anything more on this, @dullhunk

**Comment by suzanneEmbury** [comment]
So, the deploy failed ... I know why.  When I cloned the repo, it weirdly had some untracked files that were preventing me from checking out branches.  There were several image files that were untracked for some reason.  I deleted them (because untracked from a fresh clone...wot?) but now they seem to be needed by the build.

The missing files are shown below:

        images/1.4detachedHEAD.png
        images/1.4historyTab.png
        images/3.3.7showCoverageReport.png
        images/3.4.1commentOutALineOfCode.png
        images/3.4.2resultsOfRunningTheTestsOnTheModifiedCodeCompleteBuild.png
        images/pushRejectedNoHistory.png
        images/viewingtheTestCode.png

I will look at finding them and committing them later this evening - unless someone else gets to it first.

**Comment by JonasVerbickas** [comment]
I will have a look.

**Comment by JonasVerbickas** [comment]
I fixed it. GitHub actions successfully compiled and deployed the website.

**Comment by suzanneEmbury** [comment]
Great - thanks @JonasVerbickas !

**Comment by dullhunk** [comment]
thanks again for all your work on this @JonasVerbickas I've learned a little more about github actions 🙏

**Comment by suzanneEmbury** [comment]
Now that this is set up, do you want us to create pull requests on the dev branch, @dullhunk , rather than main?

That will mean we don't keep trying to deploy to netlify from our forks as well, which will be a help.  (I've switched Actions off on my fork, but having a development branch would be a more elegant solution.)

But we'll need to work out who can then merge into main (i.e. trigger a deployment) once we have a successful build on dev.  We should maybe leave that to you while we test the pipeline/workflow out?

Great to see this pipeline taking shape!

**Comment by dullhunk** [comment]
Hello @suzanneEmbury I'll set up a seperate `dev` branch which will get deployed to a different netlify URL 

In the meantime, anything you push to `UoMCS:main` gets deployed to https://software-eng.netlify.app

That's OK for tweaks, but as you say, its probably better to have a seperate `dev` branch in the longer term

(remember to fetch first obviously) cc @tmcrl

**Pull request merged**
